### PR TITLE
Let shared locks be shared again

### PR DESCRIPTION
**Pull request by matekatona**
This might not be the best solution, but I think this required the least amount of modifications. Any suggestions are welcome.

### CODE REVIEW

**Comment by matekatona** [comment]
I'll stop making this mess here, and wait for some instructions on these CI tools :D

**Comment by WoLpH** [comment]
lol, well I think you got it except that some things are platform specific. The travis builds are failing because pypiwin32 is not available on linux so that dependency should be platform dependent.

The windows version is mostly ok but it's failing some pep8 compliance checks. They can easily be checked using flake8:
```
pip install flake8
flake8 portalocker
```

To locally test everything (although I'm not sure if that works on Windows), you can try tox:
```
pip install tox
tox
```

**Comment by matekatona** [comment]
Great, I made platform specific tests. Will work on that.

The windows error is kinda weird though. I verified on my computer, that pip can't install pypiwin32 on 2.6 (it fails with an exception in `os.path.join()`, which I think is awesome). I could install it with conda, but my tests are not 2.6 compatible :D

I'm starting to like these tools, they really make you write good code.

**Comment by WoLpH** [comment]
@matekatona I've pushed out a new release thanks to @TWAC which might fix (part of) this issue already.

**Comment by WoLpH** [comment]
@matekatona can you confirm that this issue still exists?

**Comment by WoLpH** [comment]
Closed due to inactivity, I believe it's fixed already :)

I'll definitely merge in the tests though

**Comment by WoLpH** [comment]
I've merged in all of the changes and made some adjustments so it works on Python 3 as well. Thanks for the awesome work @matekatona and sorry for the slow release ;)

**Comment by matekatona** [comment]
Wow, I completely forgot about this. Unfortunately I haven't used Python for more than a year now, but I'm glad I could contribute a little. 
Thanks for cleaning up after me :)

**Comment by WoLpH** [comment]
I still appreciate it a lot, it saved me a lot of time not having to debug that part as well :)

**Pull request merged**
